---
title: "data_exploration.rmd"
author: "Fergal Stapleton"
date: "03/04/2020"
output: html_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Cloropleth Map

```{r}
#install.packages('tidyverse')
suppressWarnings(library(tidyverse))
library(lubridate)
library(magick)

# Load in data
hp <- read_csv('../data/PPR-ALL2.csv')

# Give dataset more code friendly header
names(hp) <- c("sale_date","address","post_code","county","price","nfmp","vx","desc","size_desc")

# Remove euro symbol from price values
hp$price <- gsub('[\200]','', hp$price)
hp$price <- gsub(',','', hp$price)
#hp$price <- gsub('\\.','', hp$price)

hp$price <- as.numeric(hp$price)
#hp$sale_date <- as.POSIXlt(hp$sale_date)
hp$sale_date<-dmy(hp$sale_date)
hp$year<-year(hp$sale_date)


hp <- as_tibble(hp)

# Used to insure counts are correct
nrow(hp)

# Drop complex address groupings e.g. 1-2, 4-7 Greenlane Apts ;  
complex_grouping <- hp %>%
  filter(grepl('^[0-9]+-[0-9]+.*[0-9]+-[0-9]+', address))

notable_exception <- hp %>% filter(grepl('^[0-9]+-[0-9]+.*[0-9]+\ -\ [0-9]+', address))

hp <- anti_join(hp, complex_grouping)
hp <- anti_join(hp, notable_exception)


# Drop less than a million
lessMil <- hp %>% filter(price <= 1000000)%>%
  filter(grepl('^[0-9]+-[0-9]+', address))

hp <- anti_join(hp, lessMil)

# Filter properties over a million and impute mean
filter1 <- hp %>%
  filter(price >1000000) %>%
  filter(grepl('^[0-9]+-[0-9]+', address)) %>%
  mutate(estnum = abs(parse_number(str_match(address, '^*-[0-9]+'))) 
                                - abs(parse_number(str_match(address, '^[0-9]+'))) +1 ) %>%
  mutate(imputed_mean = price/estnum)

# Want to uncount addresses
filter2 <- filter1 %>%
  uncount(estnum) %>%
  mutate(price = imputed_mean)

filter3 <- select(filter2,-c(imputed_mean))

hp <- anti_join(hp, filter1)
hp <- full_join(hp, filter3)

# Used to insure counts are correct
#nrow(filter2)

# Test join
#testout <- hp %>% filter(grepl('^[0-9]+-[0-9]+', address))

#nrow(testout)
#nrow(hp)

# Filter 2010 data and calculate means
hp2010 <-
  hp %>%
  filter(year == 2010) %>%
  group_by(county) %>%
  summarize(mean = mean(price, na.rm=TRUE))

# Filter 2020 data and calculate means
hp2020 <-
  hp %>%
  filter(year == 2020) %>%
  group_by(county) %>%
  summarize(mean = mean(price, na.rm=TRUE))

# Filter all data and calculate means
hp_means <-
  hp %>%
  group_by(county, year) %>%
  summarize(mean = mean(price, na.rm=TRUE))

quantile(hp$mean, seq(0, 1, 0.1))

price_levels <- c(60000, 120000, 180000, 240000, 300000,
                360000, 420000, 480000, 540000, 600000)
price_labels <- c('60k - 120k',   '120k - 180k', '180k - 240k', '240k - 300k',
                '300k - 360k', '360k - 420k', '420k - 480k', '480k - 540k', '540k - 600k')

colr <- colorRampPalette(c("white", "orange","red"))
colors <- colr(9)
names(colors) <- price_labels

hp_means$`Mean price` <- factor(
  cut(hp_means$mean, price_levels),
  labels = price_labels
)

# Need to match country names with country names in .shp file
hp_means$county = toupper(hp_means$county)

hp2020 <-
  hp_means %>%
  filter(year == 2020) %>%
  group_by(county) %>%
  summarize(mean = mean, `Mean price` = `Mean price`)

head(hp)
```

Next we will source and load in the shape file that we will use in our chloropleth map. The data.gov.ie website has a resource published ny the Ordnance Survey Ireland group which divides Ireland into individual counties.

Source for counties shape file:
https://data.gov.ie/dataset/counties-osi-national-statutory-boundaries-generalised-20m/resource/b412ae22-ea13-4ca3-a8be-5ffc21f455f6

```{r}
library(rgdal)
library(ggmap)
library(maptools)
library(rgeos)
library(mapproj)
ire <- readOGR(dsn='../data', 
               layer='Counties__OSi_National_Statutory_Boundaries__Generalised_20m',
               stringsAsFactors = FALSE)

names(ire)


counties <- fortify(ire, region = 'COUNTY')

#Basic plot prior to adding analysis
ggplot() +
  geom_polygon(data = counties, aes( x = long, y = lat, group = group), fill="Forest Green", color="Black") +
  theme_void() 

map_png <- function(year_var){
  ire_map <- ggplot(hp_means %>% filter(year == year_var)) +
  geom_map(aes(map_id=county, fill=`Mean price`), map=counties, color="grey") +
  coord_map() +
  expand_limits(x = counties$long, y = counties$lat) +
  labs(title=paste('Mean house price by county for ', as.character(year_var), '', sep='')) +
  labs(x = "", y = "") +
  scale_fill_manual(values = colors, drop=FALSE) +
  theme_void() +
  theme(plot.title = element_text(hjust = 0.5))
  
  # smithfield, Dundrum, Maynooth, Newbridge
  Dub_labs <- data.frame(long = c(-6.27548, -6.2535892, -6.5996, -6.8324944), 
                   lat = c(53.34780, 53.2873877, 53.3348943, 53.1798799), 
                   names = c('Dublin', '', '', ''), stringsAsFactors = FALSE)
  
  Lim_labs <- data.frame(long = c(-8.7001795, -8.7269407, -8.5637677, -9.3058371), 
                   lat = c(52.6514944, 52.5189556, 52.6731696, 52.3861802), 
                   names = c('Limerick', '', '', ''), stringsAsFactors = FALSE)
  
  costal_labs <- data.frame(long = c(-9.5270998, -8.1235273), 
                   lat = c(53.8001097, 54.6521189), 
                   names = c('', ''), stringsAsFactors = FALSE)
  
  ire_map + 
    geom_point(data = Dub_labs, mapping=aes(x=long, y=lat),color = 'blue', alpha=0.5, size = 1) + 
    geom_text(data = Dub_labs, mapping=aes(x=long, y=lat, label=names, vjust = -0.5, hjust = "center"), size = 2.2) +
    geom_point(data = Lim_labs, mapping=aes(x=long, y=lat),color = 'blue', alpha=0.5, size = 1) + 
    geom_text(data = Lim_labs, mapping=aes(x=long, y=lat, label=names, vjust = "top", hjust = "left"), size = 2.2) +
    geom_point(data = costal_labs, mapping=aes(x=long, y=lat),color = 'green', alpha=0.5, size = 1) 
  
  ggsave(paste('../png/ireland-choropleth-', year_var, '.png', sep=''), width = 4.5, height = 6, units = 'in', dpi=300, pointsize=14)
}

for (i in 2010:2020){
  map_png(i)
}

```

```{r}
# Read the individual maps into a data structure for use with 'magick'
imglayers <- sapply(c(2010:2020), function(yr) {
  image_read(paste('../png/ireland-choropleth-', yr, '.png', sep=''))
})

# Generate an animated GIF with the individual maps and write to a file
imganim <- image_animate(image_join(imglayers), fps = 1, dispose = "previous")
image_write(imganim, '../gif/ireland-choropleth-anim.gif')

imganim 
```